-- local string = "minah string com quebra \n de linha"
--
-- print(vim.inspect(vim.split(string, "\n")))

-- local tabela = { "daniel", "wellington", "santos" }
--
-- tabela[2] = "fragoso"
-- print(vim.inspect(tabela))
--
-- def
-- defp
--
-- local regex = vim.regex("^(def\\|other)")

-- local regex = vim.regex(
-- 	"^def\\|defdelegate\\|defexception\\|defguard\\|defguardp\\|defimpl\\|defmacro\\|defmacrop\\|defmodule\\|defn\\|defnp\\|defoverridable\\|defp\\|defprotocol\\|defstruct$"
-- )
--
-- print(vim.inspect(regex))
--
-- local result = regex:match_str("banana")
-- print(vim.inspect(result))
-- if nil then
-- 	print("foi")
-- end
